#!/bin/bash
# picorder-config

[ ! -d "$HOME/.local" ] && mkdir "$HOME/.local/" | tee -a "$HOME/log"
[ ! -d "$HOME/.local/bin/" ] && mkdir "$HOME/.local/bin/" | tee -a "$HOME/log"
[ ! -d "$HOME/.local/lib/" ] && mkdir "$HOME/.local/lib/" | tee -a "$HOME/log"
[ ! -d "$HOME/.local/include/" ] && mkdir "$HOME/.local/include/" | tee -a "$HOME/log"

if [ -f "$HOME/.profile" ]; then
  cd $HOME && cp .profile .profile_bkup
  grep -q "HOME/.local/bin"  ~/.profile; [ $? -eq 0 ] && echo "PATH EXIST" || echo 'PATH="$HOME/.local/bin/:$PATH"' >> ~/.profile && >> $HOME/log
else
  echo "fatal error:  "
  echo " .profile not found, Please replace or reflash raspian "
  exit
fi
