#!/bin/bash
clear

TERM=ansi 
i2c_enl=$(sudo raspi-config nonint do_i2c 1)
i2c_dis=$(sudo raspi-config nonint do_i2c 0)

{
theme="dark:0" # Theme setting dark comment to enable system colors

if [ $theme = "dark:0" ]; then
  export NEWT_COLORS='
    root=white,black
    window=white,black
    textbox=white,black
    title=white,black
    listbox=white,black
    sellistbox=black,yellow
    actsellistbox=black,yellow
    border=blue,black
    actbutton=black,green
    button=white,black
    '
fi
}
mkdir "$HOME/.local/"
mkdir "$HOME/.local/bin/"
mkdir "$HOME/.local/lib/"
mkdir "$HOME/.local/include/"

sudo apt update
sudo apt install -y git cmake
sudo apt install -y python3-pip python3-smbus sense-hat
sudo apt install -y libatlas-base-dev libopenjp2-7-dev libsdl2-dev libtiff5 libsdl-ttf2.0-dev  libsdl-gfx1.2-5 libsdl-image1.2 libsdl-kitchensink1 libsdl-mixer1.2 libsdl-sound1.2 libsdl-ttf2.0-0 libsdl1.2debian libsdl2-2.0-0 libsdl2-gfx-1.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 

# clone picorderOS repository
cd "$HOME/.local/include/" && git clone https://github.com/tearran/picorderOS.git
cd "$HOME/.local/include/picorderOS/" && python3 -m pip install -r requirements.txt

# clone picorder-config repository
cd "$HOME/.local/include/" && git clone https://github.com/Tearran/picorder-config.git
cd "$HOME/.local/include/picorder-config/" && chmod 755 "$HOME/.local/include/picorder-config/picorderOS"
cd "$HOME/.local/include/picorder-config/" && chmod 755 "$HOME/.local/include/picorder-config/picorder-config"

# clone fbcp repository
cd "$HOME/.local/include/" && git clone https://github.com/Tearran/fbcp-ili9341.git
cd "$HOME/.local/include/fbcp-ili9341" && mkdir build

# ST7735R 1.8" 160x128
cd "$HOME/.local/include/fbcp-ili9341" && cmake -DST7735R=ON -DGPIO_TFT_BACKLIGHT=18 -DGPIO_TFT_RESET_PIN=24 -DGPIO_TFT_DATA_CONTROL=23 -DSPI_BUS_CLOCK_DIVISOR=8 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=ON .. && make -j 

# ST7735S 1.8" 128x160 
#cd "$HOME/.local/include/fbcp-ili9341/build" && cmake -Wno-dev  -DST7735S=ON -DGPIO_TFT_BACKLIGHT=18 -DGPIO_TFT_RESET_PIN=27 -DGPIO_TFT_DATA_CONTROL=25 -DSPI_BUS_CLOCK_DIVISOR=30 -DDISPLAY_SWAP_BGR=ON -DSINGLE_CORE_BOARD=ON -DSTATISTICS=0 ..

# ST7789 Pimaroni Pitate audio
#cd "$HOME/.local/include/fbcp-ili9341/build" && cmake -Wno-dev -DPIRATE_AUDIO_ST7789_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=6 -DBACKLIGHT_CONTROL=ON -DSTATISTICS=1 -DUSE_DMA_TRANSFERS=OFF ..

# Compile binary
#cd "$HOME/.local/include/fbcp-ili9341/build" && make -j
# copy binary to /usr/bin
#sudo cp "$HOME/.local/include/fbcp-ili9341/build/fbcp-ili9341" "/usr/bin/fbcp"

# Install launchers 

# picorderOS Launcher for serveces
#sudo cp "$HOME/.local/include/picorder-config/picorderOS" "/usr/bin/"
# picorder-config script
#sudo cp "$HOME/.local/include/picorder-config/picorder-config" "/usr/bin/"
# Default picorderOS config file
#cp "$HOME/.local/include/picorder-config/picorder.ini" "/home/alpha/.local/include/picorderOS/picorder.ini"

[ -f /usr/bin/picorderOS ] && echo " " && echo "picorderOS launcher installed /usr/bin" ;
[ -f /usr/bin/picorderOS ] && echo " " && echo "picorder-config installed /usr/bin" && echo " " ;

echo " " && echo "System install complete...... " | echo " "

TERM=xterm

sudo "/home/alpha/.local/include/fbcp-ili9341/build/fbcp-ili9341" &
export DISPLAY=:0

exit
