#!/bin/bash

clear
export NEWT_COLORS='
root=white,black
window=white,black
textbox=white,black
title=white,black
listbox=white,black
sellistbox=black,yellow
actsellistbox=black,yellow
border=black,blue
actbutton=black,green
button=white,black'

title=" piCorderOs "
verInfo="022322.1129"

#[EN/US]
txtHelloWorld=" Hello World: "
txtWelcome="This will install and confiure piCOrderOS"
txtexit=" Exit "
txtabout=" About "
txtContinueY="Continue"
txtContinueN=" Back "
txtRequierments="Installing needed dependencies?" 
aboutConfig=" This tool aims to easly initial configuration piCorderOs. ver#: $verInfo "
txtPlzWait="Please Wait.."
txtRequierments=" This tool will install the picorderOS system, picorder-config. Use a new install or risk loosing data" #TODO About subpage
aboutconfig=" This tool aims to install the picorderOS and easly initial configuration. $verInfo "

#[Vulcan]
#txtHelloWorld="Tonk'peh panu  "
#txtexit="Ruken "
#txtabout="Pa' nash "

#[Names]
txtMenu01=" System Option    Configure System "
txtMenu02=" Display Sensors  TODO "
txtMenu03=" TODO             TODO "
txtMenu04=" TODO             TODO "
txtMenu05=" "
while [ 1 ]
do

CHOICE=$(
whiptail --fb --nocancel --title "$title" --menu "" 20 80 7 \
	"1)" "$txtMenu01" \
	"2)" "$txtMenu02" \
  "3)" "$txtMenu03" \
  "4)" "$txtMenu04" \
	"9)" "$txtabout " \
	"0)" "$txtexit "  3>&2 2>&1 1>&3
)

result=$(whoami)
case $CHOICE in
	"1)")
  		result=" TODO "
	;;
	"2)")
		  result=" TODO "
	;;
	"3)")
  		result=" TODO "
	;;
	"4)")
  		result=" TODO "
	;;
	"9)")
		  result="$aboutconfig "
        ;;
	"0)") exit
        ;;
esac
whiptail --fb --msgbox "$result" 20 60
done
exit
